### ISSUE TITLE
Relationship between height and wheel diameter and overall weight

### ISSUE THREAD

**Issue by vongomben** [remrc/Two-Axis-Reaction-Wheel-Stick#1]
Wonderful project. Have some questions:

1) How tall can it reach? 
2) IS there any relationship with the width of the wheels and the height of the overall stick? 
3) how could the wheels be more little? maybe multiplying them? 
4) Is there a relationship between the overall weight of the stick and the width of the wheels?

**Comment by remrc** [comment]
You can watch another videos.  There is a bit about what depends on what.

**Comment by vongomben** [comment]
Ok I'm checking all te other videos. 
Can you be more precised though?

thanks in advance

**Comment by remrc** [comment]
1. depends on motors, wheels weight
2. yes
3. more powerful motors, bigger wheels
4. yes, the greater the total weight, the larger (heavier) the wheels should be. It also means more powerful motors
