### ISSUE TITLE
BT Documentations

### ISSUE THREAD

**Issue by vongomben** [remrc/Two-Axis-Reaction-Wheel-Stick#2]
Hi 
From [this video](https://www.youtube.com/watch?v=vXHlW2S24GQ) I've seen a BT module.
I assume [this is ](https://github.com/remrc/Two-Axis-Reaction-Wheel-Stick/blob/main/functions.ino#L108) the sofwtare serial code receiving the data. 
Which app are you uding to control the device? 

best

**Comment by remrc** [comment]
I use the BT module to adjust the parameters. I send commands only from the serial terminal.
